"""first

Revision ID: f206cd25e878
Revises: 
Create Date: 2018-05-22 21:38:53.232390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f206cd25e878'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('netflow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f1', sa.Float(), nullable=True),
    sa.Column('f2', sa.String(length=16), nullable=True),
    sa.Column('f3', sa.String(length=16), nullable=True),
    sa.Column('f4', sa.String(length=16), nullable=True),
    sa.Column('f5', sa.Float(), nullable=True),
    sa.Column('f6', sa.Float(), nullable=True),
    sa.Column('f7', sa.Float(), nullable=True),
    sa.Column('f8', sa.Float(), nullable=True),
    sa.Column('f9', sa.Float(), nullable=True),
    sa.Column('f23', sa.Float(), nullable=True),
    sa.Column('f24', sa.Float(), nullable=True),
    sa.Column('f25', sa.Float(), nullable=True),
    sa.Column('f26', sa.Float(), nullable=True),
    sa.Column('f27', sa.Float(), nullable=True),
    sa.Column('f28', sa.Float(), nullable=True),
    sa.Column('f29', sa.Float(), nullable=True),
    sa.Column('f30', sa.Float(), nullable=True),
    sa.Column('f31', sa.Float(), nullable=True),
    sa.Column('f32', sa.Float(), nullable=True),
    sa.Column('f33', sa.Float(), nullable=True),
    sa.Column('f34', sa.Float(), nullable=True),
    sa.Column('f35', sa.Float(), nullable=True),
    sa.Column('f36', sa.Float(), nullable=True),
    sa.Column('f37', sa.Float(), nullable=True),
    sa.Column('f38', sa.Float(), nullable=True),
    sa.Column('f39', sa.Float(), nullable=True),
    sa.Column('f40', sa.Float(), nullable=True),
    sa.Column('f41', sa.Float(), nullable=True),
    sa.Column('fromIP', sa.String(length=32), nullable=True),
    sa.Column('fromPort', sa.Integer(), nullable=True),
    sa.Column('toIP', sa.String(length=32), nullable=True),
    sa.Column('toPort', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('evalue', sa.Float(), nullable=True),
    sa.Column('error', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sysinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('mem_free', sa.Integer(), nullable=True),
    sa.Column('mem_used', sa.Float(), nullable=True),
    sa.Column('net_reci', sa.Float(), nullable=True),
    sa.Column('net_send', sa.Float(), nullable=True),
    sa.Column('process', sa.Integer(), nullable=True),
    sa.Column('cpu_used', sa.Float(), nullable=True),
    sa.Column('disk_writ', sa.Float(), nullable=True),
    sa.Column('disk_read', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('logintime', sa.DateTime(), nullable=True),
    sa.Column('loginip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sysinfo')
    op.drop_table('roles')
    op.drop_table('netflow')
    op.drop_table('config')
    # ### end Alembic commands ###
